---
output:
  pdf_document
header-includes:
- \usepackage{booktabs}
params:
  a: !r 1
  b: !r 1
  c: !r 1
  d: !r 0
fontsize: 10pt
geometry: margin = 0.75in
---

\setcounter{page}{`r params$d`}

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(knitr)
library(xtable)
library(here)
library(tidyverse)
library(sf)
library(spdep)
library(tigris)
library(viridis)
library(summarytools)
library(extrafont)
options(tigris_class = "sf")
theme_set(theme_minimal())
a <- read_csv(here("dl_data", params$a)) %>%
  mutate_at(vars(GEOID), as.character)
a_trct <- st_read(here("dl_geo", "a_trct.shp")) %>%
  mutate_at(vars(GEOID), as.character)
a_puma <- st_read(here("dl_geo", "a_puma.shp")) %>%
  mutate_at(vars(GEOID), as.character)
a_cty <- st_read(here("dl_geo", "a_cty.shp")) %>%
  mutate_at(vars(GEOID), as.character)
a_taz <- st_read(here("dl_geo", "a_taz.shp")) %>%
  mutate_at(vars(GEOID), as.character)
a_tad <- st_read(here("dl_geo", "a_tad.shp")) %>%
  mutate_at(vars(GEOID), as.character)
geo_chars <- nchar(a$GEOID[1])
geo <- NULL
if(geo_chars == 11){
  geo <- "Tract"
  threshold <- 60
  study_area <- a_trct
} else if (geo_chars == 7){
  geo <- "PUMA"
  threshold <- 30
  study_area <- a_puma
} else if (geo_chars == 5){
  geo <- "County"
  threshold <- 30
  study_area <- a_cty
} else if (geo_chars == 13){
  geo <- "TAZ"
  threshold <- 60
  study_area <- a_taz
} else {
  geo <- "TAD"
  threshold <- 30
  study_area <- a_tad
}
```

```{r joins}
a <- left_join(study_area, a)
if(geo == "County"){
  a <- a %>% mutate(sp_outlier = "No")
} else {
  a_spatial <- as(a, "Spatial")
  a_nb <- poly2nb(a_spatial, queen = TRUE)
  flag <- vector()
  for(j in 1:length(a_nb)){
    sub <- a_nb[[j]]
    nb_properties <- a %>% slice(sub) %>% pull(cv) %>% mean(.)
    self_properties <- a %>% slice(j) %>% pull(cv) %>% mean(.)
    diff <- (self_properties - nb_properties) /
      ((self_properties + nb_properties) / 2) * 100
    if(diff >= 40){
      flag <- c(flag, "Yes")
      } else {
        flag <- c(flag, "No")
      }
    }
  a$sp_outlier <- flag
}
a <- a %>%
  mutate_at(vars(sp_outlier), funs(ifelse(cv > threshold, "Yes", "No"))) %>%
  mutate(cv_cat = case_when(cv <= 15 ~ "0-15",
                            cv > 15 & cv <= 30 ~ "15.1-30",
                            cv > 30 & cv <= 60 ~ "30.1-60",
                            cv > 60 ~ "60.1+"))
no_adj <- a %>% st_set_geometry(NULL) %>%
  summarize(mean(cv), median(cv), max(cv))
adj <- a %>% filter(sp_outlier == 0) %>%
  st_set_geometry(NULL) %>%
  summarize(mean(cv), median(cv), max(cv))
```

```{r main_title, results = "asis"}
cat(paste0("# ", params$c))
```

```{r second_title, results = "asis"}
cat(paste0("## ", params$b))
```

```{r third_title, results = "asis"}
cat(paste0("## ", geo))
```

### Descriptive statistics
```{r main_tab, echo = FALSE, results = "asis"}
val_sum <- a %>%
  st_set_geometry(NULL) %>%
  summarize(Minimum = min(sum_est),
            Median = median(sum_est),
            Mean = mean(sum_est),
            Maximum = max(sum_est)) %>%
  mutate_all(round, 0)
val_sum <- as.data.frame(val_sum)
cv_sum <- a %>%
  st_set_geometry(NULL) %>%
  summarize(Minimum = min(cv),
            Median = median(cv),
            Mean = mean(cv),
            Maximum = max(cv)) %>%
  mutate_all(round, 2)
cv_sum <- as.data.frame(cv_sum)
colnames(cv_tab) <- c("CV", "Count")
t1 <- kable(val_sum, format = "latex", booktabs = TRUE)
t2 <- kable(cv_sum, format = "latex", booktabs = TRUE)
cat(c("\\begin{table}[!htb]
    \\begin{minipage}{.5\\linewidth}
      \\caption{Summary of Estimates}
      \\centering",
        t1,
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}
      \\centering
        \\caption{Summary of CVs}",
        t2,
    "\\end{minipage} 
\\end{table}"
))  
```

```{r cv_tab, echo = FALSE, results = "asis"}
outlier_tab <- as.data.frame(table(a$sp_outlier))
colnames(outlier_tab) <- c("High CV Flag", "Count")
cv_tab <- as.data.frame(table(a$cv_cat))
colnames(cv_tab) <- c("CV", "Count")
t3 <- kable(cv_tab, format = "latex", booktabs = TRUE)
t4 <- kable(outlier_tab, format = "latex", booktabs = TRUE)
cat(c("\\begin{table}[!htb]
    \\begin{minipage}{.5\\linewidth}
      \\caption{CVs by Reliability Bin}
      \\centering",
        t3,
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}
      \\centering
        \\caption{High CVs}",
        t4,
    "\\end{minipage} 
\\end{table}"
))  
```

### Spatial distribution of CVs
```{r plots}
a <- a %>% mutate_at(vars(sp_outlier), as.factor)
cv_plot <- ggplot() +
  geom_sf(data = a, aes(fill = cv), color = NA) +
  coord_sf(datum = NA) +
  labs(title = "Coefficients of Variation") +
  scale_fill_viridis("CV") +
  theme(text = element_text(family = "CM Roman", size = 10))
outlier_plot <- ggplot() +
  geom_sf(data = a, aes(fill = sp_outlier), color = NA) +
  coord_sf(datum = NA) +
  labs(title = "High CVs") +
  scale_fill_manual(values = c("gainsboro", "#45055B"), name = "Outlier") +
  theme(text = element_text(family = "CM Roman", size = 10))
gridExtra::grid.arrange(cv_plot, outlier_plot, ncol = 2)
```
